language: python
python: "3.8"
sudo: required
dist: bionic
services:
  - xvfb

install:
  - pip install setuptools pyqtdeploy
  - pip install -r requirements.txt
script:
  - python -c "print('Need to write test')"
