matrix:
    include:
      - os: linux
        language: generic
        python: "3.7"
        sudo: required
        dist: bionic
        services:
          - xvfb
        before_install:
          - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.14.0-bionic
          - sudo apt-get build-dep qt5-default
          - sudo apt-get install -y libxcb-xinerama0-dev python3-pip libffi-dev libgl1-mesa-glx libnss3 libxcomposite-dev libxcursor-dev libxi6 libxtst6 libasound2 libegl1-mesa libxkbcommon-x11-0 libfontconfig1-dev libfreetype6-dev libx11-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libx11-xcb-dev libxcb-glx0-dev libxkbcommon-x11-dev qt514-meta-minimal qt514x11extras
          - sudo chmod +x /opt/qt514/bin/qt514-env.sh
          - /opt/qt514/bin/qt514-env.sh
          - export QT_QPA_PLATFORM=offscreen
        before_deploy:
          - ./scripts/generate_deb_files.sh
          - export FILE=AirbnbScanner_${TRAVIS_TAG}_i386.deb
          - mkdir pkg-debian/usr/share/AirbnbScanner
          - cp build-linux-64/AirbnbScanner pkg-debian/usr/share/AirbnbScanner/AirbnbScanner
          - dpkg -b pkg-debian/ $FILE
      - os: osx
        language: generic
        env: TOXENV=py37
        sudo: true
        before_deploy:
          - nvm install --lts
          - nvm use --lts
          - npm install -g create-dmg
          - cd dist/
          - export FILE=AirbnbScanner_${TRAVIS_TAG}.dmg
          - create-dmg 'AirbnbScanner.app' || true
          - mv AirbnbScanner\ ${TRAVIS_TAG/v}.dmg $FILE

install:
  - ./scripts/download_libraries.sh
  - pip3 install -q setuptools pyqtdeploy
  - patch -p1 -ruN -d /home/travis/.local/lib/python3.6/site-packages/pyqtdeploy < faster.patch
  - pip3 install -q -r requirements.txt
script:
  #- python3 build.py --verbose
  - pyqtdeploy-sysroot --source-dir /opt/qt514/ --source-dir ${PWD} --target linux-64 --sysroot sysroot-linux-64 --verbose sysroot.json

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GH_TOKEN
  file:
    - $FILE
  on:
    tags: true
