platform:
  - x64

image: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
      PATH: C:\Program Files (x86)\NSIS\;%PATH%

artifacts:
  - path: AirbnbScanner_%APPVEYOR_REPO_TAG_NAME%_setup.exe

build: off

init:
  #- cmd: copy C:\windows\system32\libeay32.dll C:\Qt\5.14.0\msvc2017_64\bin
  #- cmd: copy C:\windows\system32\ssleay32.dll C:\Qt\5.14.0\msvc2017_64\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;C:\Qt\5.14.0\msvc2017_64\bin;%PATH%
  - python -m pip install --upgrade pip setuptools virtualenv

install:
  - curl -LO https://www.zlib.net/fossils/zlib-1.2.11.tar.gz
  - curl -LO https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
  - curl -LO https://www.riverbankcomputing.com/static/Downloads/sip/4.19.20/sip-4.19.20.tar.gz
  - curl -LO https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz
  - curl -LO https://ftp.openssl.org/source/old/1.1.0/openssl-1.1.0j.tar.gz
  - virtualenv venv
  - venv\Scripts\activate
  - pip install pyqtdeploy
  - pip install -r requirements.txt

test_script:
  - python build.py --installed-qt-dir C:\Qt\5.14.0 --verbose

after_test:
  - ps: $size = [math]::floor((Get-ChildItem dist\ -Recurse | Measure-Object -Sum Length | Select-Object -ExpandProperty Sum)/1000)
  - ps: if ($env:APPVEYOR_REPO_TAG_NAME) { $tag = $env:APPVEYOR_REPO_TAG_NAME } else { $tag="v0.0.0" }
  - ps: $major, $minor, $build = $tag.substring(1).split(".")
  - ps: makensis.exe /DTAG=$tag /DSIZE=$size /DMAJOR=$major /DMINOR=$minor /DBUILD=$build airbnbscanner.nsi

deploy:
  provider: GitHub
  auth_token:
    secure: 6eX2olaIxe4TsfETod+SYOyDsIKwmDivjirb7RPvl/Zd4zYW3dzGr4MieJ2BP89P # your encrypted token from GitHub
  artifact: AirbnbScanner_%APPVEYOR_REPO_TAG_NAME%_setup.exe
  prerelease: true
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
