#!/bin/sh
ln -s /usr/share/AirbnbScanner/AirbnbScanner /usr/bin/AirbnbScanner
setcap cap_net_raw=eip /usr/share/AirbnbScanner/AirbnbScanner
touch /etc/ld.so.conf.d/airbnb-scanner.conf

cat > /etc/ld.so.conf.d/airbnb-scanner.conf << EOF
#LIBRARY FOR AIRBNB SCANNER BECAUSE LD_LIBRARY_PATH CANT BE USE WITH setcap
/usr/share/AirbnbScanner
EOF

ldconfig
