wget https://www.zlib.net/fossils/zlib-1.2.11.tar.gz
wget http://download.qt.io/official_releases/qt/5.12/5.12.2/single/qt-everywhere-src-5.12.2.tar.xz
wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
wget https://www.riverbankcomputing.com/static/Downloads/sip/4.19.15/sip-4.19.15.tar.gz
wget https://www.riverbankcomputing.com/static/Downloads/PyQt5/5.12.1/PyQt5_gpl-5.12.1.tar.gz
wget https://www.riverbankcomputing.com/static/Downloads/PyQt3D/5.12/PyQt3D_gpl-5.12.tar.gz
wget https://www.riverbankcomputing.com/static/Downloads/PyQtChart/5.12/PyQtChart_gpl-5.12.tar.gz
wget https://www.riverbankcomputing.com/static/Downloads/PyQtDataVisualization/5.12/PyQtDataVisualization_gpl-5.12.tar.gz
wget https://www.riverbankcomputing.com/static/Downloads/PyQtPurchasing/5.12/PyQtPurchasing_gpl-5.12.tar.gz
wget https://www.riverbankcomputing.com/static/Downloads/QScintilla/2.11.1/QScintilla_gpl-2.11.1.tar.gz
wget https://ftp.openssl.org/source/old/1.0.2/openssl-1.0.2r.tar.gz
